"""
Cross-platform transfer learning evaluator.

Runs the same MITRE technique across all three VMs (Linux, macOS, Windows)
using platform-specific command variants generated by the LLM.

This demonstrates that the model has learned abstract vulnerability patterns
that transfer across OS boundaries — not just memorized specific commands.

Thesis metric: cross-platform success rate (fraction of techniques that succeed
on ALL three platforms, using a model trained primarily on Linux data).

Usage:
    executor = CrossPlatformExecutor()
    report = executor.run("T1082")
    print(report.summary())
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


@dataclass
class PlatformResult:
    platform: str
    vm_name: str
    command: str
    exit_code: int
    stdout: str
    ioc_confidence: float
    success: bool
    duration_s: float


@dataclass
class CrossPlatformReport:
    technique_id: str
    results: dict[str, PlatformResult] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    @property
    def platforms_tested(self) -> list[str]:
        return list(self.results.keys())

    @property
    def platforms_succeeded(self) -> list[str]:
        return [p for p, r in self.results.items() if r.success]

    @property
    def transfer_score(self) -> float:
        """Fraction of tested platforms where the technique succeeded."""
        if not self.results:
            return 0.0
        return len(self.platforms_succeeded) / len(self.results)

    @property
    def full_success(self) -> bool:
        return len(self.platforms_succeeded) == len(self.results)

    def summary(self) -> str:
        lines = [
            f"Cross-Platform Report: {self.technique_id}",
            f"  Transfer score: {self.transfer_score:.2f} "
            f"({len(self.platforms_succeeded)}/{len(self.results)} platforms)",
            "",
        ]
        for platform, result in self.results.items():
            status = "SUCCESS" if result.success else "FAIL"
            lines.append(
                f"  [{status:7s}] {platform:8s} | IOC confidence={result.ioc_confidence:.2f} "
                f"| exit={result.exit_code} | {result.duration_s:.1f}s"
            )
            if result.command:
                lines.append(f"           Command: {result.command[:80]}")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "technique_id": self.technique_id,
            "transfer_score": self.transfer_score,
            "full_success": self.full_success,
            "timestamp": self.timestamp,
            "results": {
                p: {
                    "platform": r.platform,
                    "command": r.command,
                    "success": r.success,
                    "ioc_confidence": r.ioc_confidence,
                    "exit_code": r.exit_code,
                }
                for p, r in self.results.items()
            },
        }


# Platforms to test in order of expected difficulty
PLATFORM_MAP = [
    ("linux",   "linux"),
    ("macos",   "macos"),
    ("windows", "windows"),
]


class CrossPlatformExecutor:
    """
    Executes a technique on all three VMs and compares results.

    The key insight: the model must generate syntactically different commands
    per platform (bash vs PowerShell vs zsh) while targeting the same semantic
    technique. Successful transfer = technique works on all three.
    """

    def __init__(self, adapter_name: Optional[str] = "red_team"):
        self.adapter_name = adapter_name

    def run(
        self,
        technique_id: str,
        platforms: list[str] | None = None,
    ) -> CrossPlatformReport:
        """
        Run a single technique across multiple platforms.

        Args:
            technique_id: MITRE technique ID (e.g. "T1082")
            platforms:    Subset of ["linux", "macos", "windows"] to test;
                          None = all three
        """
        from tools.security_tools import generate_test_oneliner
        from tools.ssh_executor import get_ssh_pool
        from tools.ioc_collector import get_ioc_collector
        from tools.vm_tools import get_vm_manager
        from config import VMS

        ssh_pool = get_ssh_pool()
        ioc_collector = get_ioc_collector()
        vm_mgr = get_vm_manager()

        test_platforms = [
            (plat, vm) for plat, vm in PLATFORM_MAP
            if platforms is None or plat in platforms
        ]

        report = CrossPlatformReport(technique_id=technique_id)

        for platform, vm_name in test_platforms:
            cfg = VMS.get(vm_name, {})
            # Skip if VM IP is not configured
            if not cfg.get("host") and cfg.get("backend") == "tart":
                print(f"  [{platform}] Skipped (VM IP not configured)")
                continue

            print(f"  [{platform}] Generating command for {technique_id}...")
            t0 = time.monotonic()

            # Generate platform-specific command
            cmd_result = generate_test_oneliner.invoke({
                "technique_id": technique_id,
                "target_os": platform,
                "context": "Executable command, no placeholders",
            })

            # Extract the actual command from the result
            command = self._extract_command(cmd_result, platform)

            if not command:
                print(f"  [{platform}] No command generated")
                continue

            # Snapshot
            actual_name = cfg.get("vm_name", vm_name)
            backend = cfg.get("backend", "tart")
            try:
                vm_mgr.snapshot(actual_name, backend=backend)
            except Exception:
                pass

            # Execute
            try:
                exec_result = ssh_pool.execute(vm_name, command, timeout=60)
                exit_code = exec_result.exit_code
                stdout = exec_result.stdout[:500]
                exec_ok = exec_result.success
            except Exception as exc:
                exit_code = -1
                stdout = f"SSH error: {exc}"
                exec_ok = False

            # Collect IOCs
            try:
                ioc_report = ioc_collector.collect(ssh_pool, vm_name, technique_id, platform)
                confidence = ioc_report.confidence
            except Exception:
                confidence = 0.1 if exec_ok else 0.0

            duration = time.monotonic() - t0
            success = confidence >= 0.4 or (exec_ok and exit_code == 0)

            report.results[platform] = PlatformResult(
                platform=platform,
                vm_name=vm_name,
                command=command,
                exit_code=exit_code,
                stdout=stdout,
                ioc_confidence=confidence,
                success=success,
                duration_s=duration,
            )

            status = "SUCCESS" if success else "FAIL"
            print(f"  [{platform}] {status} — IOC confidence={confidence:.2f}")

            # Restore
            try:
                vm_mgr.restore(actual_name, f"{actual_name}-clean", backend=backend)
            except Exception:
                pass

        return report

    def _extract_command(self, llm_result: str, platform: str) -> str:
        """Pull the executable command from the LLM/tool result."""
        lines = llm_result.strip().splitlines()
        # Skip comment/context lines starting with #
        for line in lines:
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and not stripped.startswith("Retrieved"):
                return stripped
        return lines[0].strip() if lines else ""

    def run_batch(
        self,
        technique_ids: list[str],
        platforms: list[str] | None = None,
    ) -> dict[str, CrossPlatformReport]:
        """Run cross-platform transfer test for multiple techniques."""
        import json
        from pathlib import Path

        results: dict[str, CrossPlatformReport] = {}
        print(f"\n{'='*60}")
        print(f"Cross-Platform Transfer Test: {len(technique_ids)} techniques")
        print(f"{'='*60}")

        for tech_id in technique_ids:
            print(f"\n[{tech_id}]")
            report = self.run(tech_id, platforms=platforms)
            results[tech_id] = report
            print(f"  Transfer score: {report.transfer_score:.2f}")

        # Summary statistics
        scores = [r.transfer_score for r in results.values()]
        if scores:
            import numpy as np
            print(f"\nOverall Transfer Score: {np.mean(scores):.2f} ± {np.std(scores):.2f}")
            full_successes = sum(1 for r in results.values() if r.full_success)
            print(f"Full cross-platform success: {full_successes}/{len(results)}")

        # Save results
        out_dir = Path("data/cross_platform")
        out_dir.mkdir(parents=True, exist_ok=True)
        with open(out_dir / "results.json", "w") as f:
            json.dump({k: v.to_dict() for k, v in results.items()}, f, indent=2)
        print(f"\nResults saved to {out_dir}/results.json")

        return results
